// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: pipeline.proto

#include "pipeline.pb.h"
#include "pipeline.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace pipeline {

static const char* PipelineService_method_names[] = {
  "/pipeline.PipelineService/Start",
  "/pipeline.PipelineService/Stop",
};

std::unique_ptr< PipelineService::Stub> PipelineService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PipelineService::Stub> stub(new PipelineService::Stub(channel, options));
  return stub;
}

PipelineService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Start_(PipelineService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stop_(PipelineService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PipelineService::Stub::Start(::grpc::ClientContext* context, const ::pipeline::StartRequest& request, ::pipeline::CommonReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pipeline::StartRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Start_, context, request, response);
}

void PipelineService::Stub::async::Start(::grpc::ClientContext* context, const ::pipeline::StartRequest* request, ::pipeline::CommonReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pipeline::StartRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, std::move(f));
}

void PipelineService::Stub::async::Start(::grpc::ClientContext* context, const ::pipeline::StartRequest* request, ::pipeline::CommonReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pipeline::CommonReply>* PipelineService::Stub::PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::pipeline::StartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pipeline::CommonReply, ::pipeline::StartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Start_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pipeline::CommonReply>* PipelineService::Stub::AsyncStartRaw(::grpc::ClientContext* context, const ::pipeline::StartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PipelineService::Stub::Stop(::grpc::ClientContext* context, const ::pipeline::StopRequest& request, ::pipeline::CommonReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::pipeline::StopRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Stop_, context, request, response);
}

void PipelineService::Stub::async::Stop(::grpc::ClientContext* context, const ::pipeline::StopRequest* request, ::pipeline::CommonReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::pipeline::StopRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void PipelineService::Stub::async::Stop(::grpc::ClientContext* context, const ::pipeline::StopRequest* request, ::pipeline::CommonReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pipeline::CommonReply>* PipelineService::Stub::PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::pipeline::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::pipeline::CommonReply, ::pipeline::StopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Stop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::pipeline::CommonReply>* PipelineService::Stub::AsyncStopRaw(::grpc::ClientContext* context, const ::pipeline::StopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

PipelineService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PipelineService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PipelineService::Service, ::pipeline::StartRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PipelineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pipeline::StartRequest* req,
             ::pipeline::CommonReply* resp) {
               return service->Start(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PipelineService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PipelineService::Service, ::pipeline::StopRequest, ::pipeline::CommonReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PipelineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::pipeline::StopRequest* req,
             ::pipeline::CommonReply* resp) {
               return service->Stop(ctx, req, resp);
             }, this)));
}

PipelineService::Service::~Service() {
}

::grpc::Status PipelineService::Service::Start(::grpc::ServerContext* context, const ::pipeline::StartRequest* request, ::pipeline::CommonReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PipelineService::Service::Stop(::grpc::ServerContext* context, const ::pipeline::StopRequest* request, ::pipeline::CommonReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pipeline

